#!/usr/bin/env bash
#
# build.sh -- one-step build for the Julia binding's libitb3.so
# dependency. Prerequisites (Go, Julia 1.10+) must be installed
# separately; see README.md "Prerequisites" section.
#
# Every artefact this binding owns is removed before the build, so
# nothing in the tree predates the invocation. eitb/eitb runs its Julia
# entry point directly against this project, so it has no compiled
# output of its own: the guarantee for it is that the project resolves
# and precompiles from a wiped Manifest on every invocation.
#
# Usage:
#   ./build.sh             # default build (full asm stack)
#   ./build.sh --noitbasm  # opt out of ITB's SIMD asm kernels
#                          # (use on hosts without AVX-512+VL)
#
# Environment:
#   ITB_SKIP_CLEAN=1       # keep existing artefacts (fast iteration)
#   ITB_KEEP_DOWNLOADS=1   # keep fetched dependency trees

set -eu
set -o pipefail

cd "$(dirname "$0")"
REPO_ROOT="$(cd ../.. && pwd)"

TAGS=()
case "${1:-}" in
    --noitbasm) TAGS=(-tags=noitbasm); shift;;
    -h|--help)  echo "usage: $0 [--noitbasm]"; exit 0;;
    "")         ;;
    *)          echo "unknown option: $1" >&2; exit 2;;
esac

# ---- artefact wipe ---------------------------------------------------
# The build starts from nothing: every artefact this binding owns is
# removed before anything is rebuilt, so no output can predate this
# invocation. ITB_SKIP_CLEAN=1 skips the wipe for fast iteration.
#
# Fetched dependency trees and registry-resolved lock files need network
# to restore, so ITB_KEEP_DOWNLOADS=1 preserves them. That is the weaker
# guarantee: a stale dependency can still mask breakage, and only the
# artefacts this binding compiles itself are then known to be fresh.
#
# Deletion safety: clean_target takes a path relative to this binding's
# own directory. An empty path, an absolute path, or one containing ".."
# is refused outright, and the resolved target is re-checked to lie
# inside the binding directory before removal -- so the wipe cannot
# reach the shared dist/linux-amd64/libitb3.so, the user's Julia depot,
# or anything else outside this directory. Every removal is logged first.
BINDING_DIR="$(pwd -P)"

# Subtrees, relative to this binding, that a pattern sweep must not
# descend into. A dependency tree preserved by ITB_KEEP_DOWNLOADS sits
# inside this directory, so without this the sweep would reach into the
# very tree the flag is there to protect.
CLEAN_PRUNE=()

clean_target() {
    local rel="$1" abs res
    case "$rel" in
        ""|/*|*..*)
            echo "[clean] refusing unsafe target: '$rel'" >&2
            exit 1
            ;;
    esac
    abs="$BINDING_DIR/$rel"
    [ -e "$abs" ] || [ -L "$abs" ] || return 0
    res="$(readlink -f "$abs")"
    case "$res" in
        "$BINDING_DIR"/*) ;;
        *)
            echo "[clean] refusing target outside $BINDING_DIR: $res" >&2
            exit 1
            ;;
    esac
    echo "[clean] rm -rf $abs"
    rm -rf "$abs"
}

# Remove every entry matching a name pattern anywhere below this
# binding's directory, skipping the CLEAN_PRUNE subtrees. Matches are
# collected before the first removal so the walk is not racing the
# deletions.
clean_tree() {
    local pattern="$1" hit prune
    local -a args=("$BINDING_DIR") hits=()
    for prune in ${CLEAN_PRUNE+"${CLEAN_PRUNE[@]}"}; do
        args+=(-path "$BINDING_DIR/$prune" -prune -o)
    done
    args+=(-name "$pattern" -print0)
    while IFS= read -r -d '' hit; do
        hits+=("$hit")
    done < <(find "${args[@]}")
    for hit in "${hits[@]}"; do
        clean_target "${hit#"$BINDING_DIR"/}"
    done
}

if [[ "${ITB_SKIP_CLEAN:-0}" == "1" ]]; then
    echo "==> ITB_SKIP_CLEAN=1: keeping the existing artefacts"
else
    echo "==> removing the artefacts owned by this binding"
    # Manifest.toml is regenerated by Pkg.instantiate below. The only
    # declared dependency is a Julia stdlib, but Pkg still refreshes the
    # General registry while re-resolving, so the wipe is not proven to
    # be offline-safe; ITB_KEEP_DOWNLOADS=1 preserves the Manifest for a
    # host where that refresh cannot reach the network.
    if [[ "${ITB_KEEP_DOWNLOADS:-0}" == "1" ]]; then
        echo "[clean] ITB_KEEP_DOWNLOADS=1: keeping Manifest.toml (weaker guarantee)"
    else
        clean_target 'Manifest.toml'
    fi
    clean_target '.julia'
    clean_target 'bench/build'
    clean_tree '*.ji'
    clean_tree '*.cov'
    # The package's precompile cache lives in the user's own Julia depot
    # outside this directory and is therefore never touched here; Julia
    # keys those entries on source content, so a stale one cannot be
    # loaded against changed sources.
fi

cd "$REPO_ROOT"
echo "==> building libitb3.so${TAGS:+ (with ${TAGS[*]})}"
go build -trimpath "${TAGS[@]}" -buildmode=c-shared \
    -o dist/linux-amd64/libitb3.so ./cmd/cshared

cd "$REPO_ROOT/bindings/julia"
echo "==> resolving + precompiling the ITB Julia package"
julia --startup-file=no --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

echo "==> Julia binding loads libitb3.so at runtime via Libdl; no further build step."
echo "==> ready: ./run_tests.sh"
